### ISSUE TITLE
Главное меню не отображается в мобильной версии

### ISSUE THREAD

**Issue by karamans** [Teplitsa/kandinsky#20]
Здравствуйте. Только что установил последнюю версию темы, в главном меню нет ни одного пункта

**Comment by ionburdianov** [comment]
> с

Здравствуйте!

К сожалению отвечаю слишком поздно, но все таки уточните пожалуйста ваш вопрос еще актуален или я могу закрыть проблему?

**Comment by ionburdianov** [comment]
@karamans по причине что от вас долгое время нет ответа, закрываем данный issue.

Но все таки отвечу здесь на самые частые причины по которой может не отображается меню на сайте.

Проверьте если в разделе **Внешний вид > Меню - Ваше меню**, включена ли Область отображения - Главное меню.
![image](https://github.com/Teplitsa/kandinsky/assets/28696444/02cd964c-8f77-4406-b95a-52bebd0aaec1)

Проверьте в **Внешний вид > Настроить > Шапка**, если включены настройки отображения меню, как для десктопа так и для мобильного меню.
![image](https://github.com/Teplitsa/kandinsky/assets/28696444/bc4dc92d-e042-4a05-ba9d-9fa4e3ae4d9e)
