### ISSUE TITLE
В блоке Партнёры новое поведение

### ISSUE THREAD

**Issue by kovalexpro** [Teplitsa/kandinsky#22]
При попытке вставить нового партнёра, ссылка, обрамляющая его лого, более не ведёт на сайт партнёра, а указывает на головной сайт. Инструкция https://github.com/Teplitsa/kandinsky/wiki/%D0%91%D0%BB%D0%BE%D0%BA-%C2%AB%D0%9F%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D1%8B%C2%BB не соответствует реалиям, в частности, нет поля "Отрывок" или какого-либо схожего поля.

**Comment by ionburdianov** [comment]
@kovalexpro мы не успели еще обновить документацию и там выводится информация для старой версии темы еще.

На данный момент ссылка партнера уже не указывается в поле "Отрывок" а в новое поле "URL-адрес партнера"
![image](https://user-images.githubusercontent.com/28696444/164484419-e4fdfa6b-59a0-464f-8acc-a7b1021ff544.png)

**Comment by kovalexpro** [comment]
на самом деле, на сайте была версия 2.0.0.x и я обновил её до 2.1.6 кажется и всё заработало!
спасибо за комментарий, именно это поле я и использовал изначально.
