### ISSUE TITLE
Есть ли возможность / документация установки темы и конфигурирования из консоли / wp-cli?

### ISSUE THREAD

**Issue by vadimkantorov** [Teplitsa/kandinsky#23]
Ищу возможность настройки темы и добавления контента чисто через консоль / wp-cli

Спасибо!

**Comment by vadimkantorov** [comment]
`wp theme install --activate https://knd.te-st.ru/kandinsky.zip` работает успешно

теперь вопрос, как настраивать тему из консоли и добавлять контент

**Comment by ionburdianov** [comment]
Если вы спрашивайте как импортировать демо контент то его можно только через интерфейс WordPress, запустив Мастер настроек из меню Внешний вид.
![image](https://github.com/Teplitsa/kandinsky/assets/28696444/6ba7f0df-588a-4de8-9099-3a0456afd3a8)

**Comment by vadimkantorov** [comment]
Я спрашиваю про конфигурирование темы в широком смысле. То есть отдельной subcommand для wp-cli вы не предоставляете, правильно?

Я думаю, что все эти настройки можно задавать и через wp-cli (команда option set), так как wp-cli просто сохраняет опции в таблицу wp_options. Но было бы полезно иметь пример для настройки темы через wp-cli

**Comment by vadimkantorov** [comment]
Правильно я понимаю, что все настройки темы Кандинский хранятся в итоге в БД в стандартной таблице wp_options?

**Comment by ionburdianov** [comment]
> Я спрашиваю про конфигурирование темы в широком смысле. То есть отдельной subcommand для wp-cli вы не предоставляете, правильно?
> 
> Я думаю, что все эти настройки можно задавать и через wp-cli (команда option set), так как wp-cli просто сохраняет опции в таблицу wp_options. Но было бы полезно иметь пример для настройки темы через wp-cli

Идея конечно интересная, но тема Kandinsky предусмотрена для обычных пользователей.

**Comment by ionburdianov** [comment]
> Правильно я понимаю, что все настройки темы Кандинский хранятся в итоге в БД в стандартной таблице wp_options?

Да.

**Comment by vadimkantorov** [comment]
Понял, спасибо!

Нет ли кстати у вас какого-то WXR-файла или дампа БД для демо-контента/демо-конфигурации?

**Comment by vadimkantorov** [comment]
> Идея конечно интересная, но тема Kandinsky предусмотрена для обычных пользователей.

Я просто пытаюсь сделать некий SSG-движок из вордпресса с импортом настроек и контента (из markdown-постов) в базу в момент генерации статического сайта (для простых сайтов-визиток НКО блогового типа). В принципе это всё удалось сделать.

**Comment by vadimkantorov** [comment]
Вот такой стек-трейс теперь вылазит после установки kandinsky при использовании команд wp-cli:
```
Warning: Some code is trying to do a URL redirect. Backtrace:
#0 /home/runner/work/wpssg/wpssg/wp-includes/class-wp-hook.php(326): WP_CLI\Utils\wp_redirect_handler('...')
#1 /home/runner/work/wpssg/wpssg/wp-includes/plugin.php(205): WP_Hook->apply_filters('...', Array)
#2 /home/runner/work/wpssg/wpssg/wp-includes/pluggable.php(1396): apply_filters('...', '...', 302)
#3 /home/runner/work/wpssg/wpssg/wp-includes/pluggable.php(1545): wp_redirect('...', 302, '...')
#4 /home/runner/work/wpssg/wpssg/wp-content/themes/kandinsky/core/extras.php(157): wp_safe_redirect('...')
#5 /home/runner/work/wpssg/wpssg/wp-includes/class-wp-hook.php(326): knd_after_theme_activation('...')
#6 /home/runner/work/wpssg/wpssg/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /home/runner/work/wpssg/wpssg/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /home/runner/work/wpssg/wpssg/wp-includes/theme.php(3504): do_action('...', '...', Object(WP_Theme))
#9 /home/runner/work/wpssg/wpssg/wp-includes/class-wp-hook.php(324): check_theme_switched('')
#10 /home/runner/work/wpssg/wpssg/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#11 /home/runner/work/wpssg/wpssg/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/runner/work/wpssg/wpssg/wp-settings.php(700): do_action('...')
#13 phar:///home/runner/work/wpssg/wpssg/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1375): require('...')
#14 phar:///home/runner/work/wpssg/wpssg/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(12[94](https://github.com/vadimkantorov/wpssg/actions/runs/11274153472/job/31352696039#step:6:95)): WP_CLI\Runner->load_wordpress()
#15 phar:///home/runner/work/wpssg/wpssg/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#16 phar:///home/runner/work/wpssg/wpssg/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#17 phar:///home/runner/work/wpssg/wpssg/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#18 phar:///home/runner/work/wpssg/wpssg/wp-cli.phar/php/boot-phar.php(20): include('...')
#19 /home/runner/work/wpssg/wpssg/wp-cli.phar(4): include('...')
```

(полный код скрипта тут: https://github.com/vadimkantorov/wpssg/blob/master/.github/workflows/publish.yml)
