### ISSUE TITLE
HTTP error 500 после активации темы

### ISSUE THREAD

**Issue by MemorialMoscow** [Teplitsa/kandinsky#3]
[error_log.txt](https://github.com/Teplitsa/kandinsky/files/1315108/error_log.txt)
При установке темы поверх свежей инсталляции Wordpress 4.8.1 сайт падает с 500й ошибкой сразу после активации темы, предпросмотр также выдает 500ю.

Хостинг: выделенный сервер на masterhost (Debian 7.11), PHP 5.3, MySQL 5.6.

Другие сторонние темы устанавливаются и активируются без проблем.

Если нужен доступ к площадке (SSH, FTP и phpmyadmin) - пишите на administrator@memo.ru или в Telegram @amitkovskiy.

**Comment by MemorialMoscow** [comment]
Поставил версию, лежащую тут: https://github.com/Teplitsa/kandinsky/archive/master.zip

Пока что с тем же результатом (см. лог).
[error_log.txt](https://github.com/Teplitsa/kandinsky/files/1318197/error_log.txt)

**Comment by Ahaenor** [comment]
Ок, спасибо, исправлено.
Код в ветке master готов к установке.

**Comment by MemorialMoscow** [comment]
Поставил. См. лог.
[error_log.txt](https://github.com/Teplitsa/kandinsky/files/1318304/error_log.txt)

**Comment by Ahaenor** [comment]
Спасибо ещё раз. Сейчас все ошибки совместимости с PHP 5.3 устранены - пожалуйста, попробуйте ещё раз.

**Comment by MemorialMoscow** [comment]
Инсталлируется.
