### ISSUE TITLE
При просмотре сайта с мобильного устройства не отображается название сайта

### ISSUE THREAD

**Issue by yaklik** [Teplitsa/kandinsky#4]
Хотя при просмотре с ПК всё нормально.
![4458f0bb-0948-4fb3-9e27-d289eff23ecc](https://user-images.githubusercontent.com/48753326/54677880-e67ea780-4b14-11e9-8d8b-b5b43afe4f3f.jpg)

**Comment by ionburdianov** [comment]
Если на сайте загружен логотип то в мобильной версии название сайта скрывается, потому что в большинстве случаев название длинное и не помещается в шапке.
